import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export type InvoicePdfPayment = {
  id: string;
  amount: number;
  baseAmount?: number | null;
  currency: string;
  status: string;
  paymentMethod?: string | null;
  reference?: string | null;
  notes?: string | null;
  paidAt?: string | null;
  createdAt: string;
  gateway?: string | null;
};

export type InvoicePdfData = {
  invoiceNumber: string;
  packageName: string;
  billingCycle: string;
  currency: string;
  amount: number;
  amountPaid: number;
  balanceDue: number;
  status: string;
  invoiceDate: string;
  dueDate: string;
  servicePeriodStart: string;
  servicePeriodEnd: string;
  notes?: string | null;
  terms?: string | null;
  payments?: InvoicePdfPayment[];
  package?: { displayName?: string | null } | null;
  ministryAdmin?: {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    ministryName?: string | null;
  } | null;
};

function formatMoney(currency: string, value?: number | null) {
  return `${currency} ${(value ?? 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}`;
}

function formatDate(value?: string | null) {
  return value ? new Date(value).toLocaleDateString() : '-';
}

function safeFileName(value: string) {
  return value.replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase();
}

export function downloadPackageInvoicePdf(invoice: InvoicePdfData, billedToFallback = 'Ministry account') {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const packageName = invoice.package?.displayName || invoice.packageName;
  const billedTo = invoice.ministryAdmin?.ministryName
    || `${invoice.ministryAdmin?.firstName ?? ''} ${invoice.ministryAdmin?.lastName ?? ''}`.trim()
    || invoice.ministryAdmin?.email
    || billedToFallback;

  doc.setFontSize(18);
  doc.text('ICIMS Package Invoice', 14, 18);
  doc.setFontSize(10);
  doc.text(`Invoice: ${invoice.invoiceNumber}`, 14, 26);
  doc.text(`Status: ${invoice.status.replace('_', ' ')}`, 14, 32);

  doc.setFontSize(11);
  doc.text('Billed To', 14, 45);
  doc.setFontSize(10);
  doc.text(billedTo, 14, 51);
  if (invoice.ministryAdmin?.email) doc.text(invoice.ministryAdmin.email, 14, 57);

  autoTable(doc, {
    startY: 68,
    head: [['Field', 'Value']],
    body: [
      ['Package', packageName],
      ['Billing cycle', invoice.billingCycle],
      ['Invoice date', formatDate(invoice.invoiceDate)],
      ['Due date', formatDate(invoice.dueDate)],
      ['Service period', `${formatDate(invoice.servicePeriodStart)} - ${formatDate(invoice.servicePeriodEnd)}`],
      ['Amount', formatMoney(invoice.currency, invoice.amount)],
      ['Paid', formatMoney(invoice.currency, invoice.amountPaid)],
      ['Balance due', formatMoney(invoice.currency, invoice.balanceDue)],
    ],
    styles: { fontSize: 9 },
    headStyles: { fillColor: [32, 44, 60] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 45 } },
  });

  let startY = (doc as any).lastAutoTable.finalY + 10;
  const payments = invoice.payments ?? [];
  if (payments.length) {
    autoTable(doc, {
      startY,
      head: [['Date', 'Method', 'Reference', 'Status', 'Amount']],
      body: payments.map(payment => [
        formatDate(payment.paidAt || payment.createdAt),
        payment.paymentMethod || payment.gateway || 'payment',
        payment.reference || '-',
        payment.status,
        formatMoney(payment.currency, payment.baseAmount ?? payment.amount),
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [32, 44, 60] },
    });
    startY = (doc as any).lastAutoTable.finalY + 10;
  }

  const notes = [invoice.notes, invoice.terms].filter(Boolean) as string[];
  if (notes.length) {
    doc.setFontSize(10);
    notes.forEach((text, index) => {
      const label = index === 0 && invoice.notes ? 'Notes' : 'Terms';
      const lines = doc.splitTextToSize(`${label}: ${text}`, 180);
      if (startY + lines.length * 5 > 280) {
        doc.addPage();
        startY = 18;
      }
      doc.text(lines, 14, startY);
      startY += lines.length * 5 + 4;
    });
  }

  doc.setFontSize(8);
  doc.text('Generated by ICIMS', 14, 287);
  doc.save(`${safeFileName(invoice.invoiceNumber)}.pdf`);
}
