export const PACKAGE_FEATURES = {
  GIVING_TRACKING: 'giving_tracking',
  GIVING_CAMPAIGNS: 'giving_campaigns',
  GIVING_MANUAL_RECORDS: 'giving_manual_records',
  GIVING_ONLINE_PAYMENTS: 'giving_online_payments',
  GIVING_PUBLIC_LINKS: 'giving_public_links',
  GIVING_QR_CODES: 'giving_qr_codes',
  GIVING_WALLETS: 'giving_wallets',
  GIVING_WITHDRAWALS: 'giving_withdrawals',
  GIVING_CELL_OFFERING: 'giving_cell_offering',
  PLEDGES_MANAGEMENT: 'pledges_management',
  TRANSACTIONS_VIEW: 'transactions_view',
  EVENTS_MANAGEMENT: 'events_management',
  EVENT_PUBLIC_LINKS: 'event_public_links',
  EVENT_QR_CODES: 'event_qr_codes',
  EVENT_MEMBER_BOOKING: 'event_member_booking',
  EVENT_GUEST_BOOKING: 'event_guest_booking',
  EVENT_TICKETING: 'event_ticketing',
  EVENT_ONLINE_PAYMENTS: 'event_online_payments',
  EVENT_MANUAL_PAYMENTS: 'event_manual_payments',
  EVENT_ATTENDANCE: 'event_attendance',
  EVENT_TICKET_SCANNING: 'event_ticket_scanning',
  EVENT_REPORTS: 'event_reports',
} as const;
